external-dns:

  provider: pihole

  # Nom du domaine que tu veux gérer
  domainFilters:
    - "cluster.local"

  # URL de ton Pi-hole (souvent http://<ip>/admin ou https://<dns>/admin)
  pihole:
    server: "http://192.168.1.106/admin"
