external-dns:

  image:  # @schema additionalProperties: false
    tag:  v20251024-v0.19.0-64-g994f4dc2
    repository: gcr.io/k8s-staging-external-dns/external-dns

  provider: pihole

  logLevel: debug
  policy: sync
  registry: txt
  txtOwnerId: "k8s"
  interval: "1m"

  sources:
    - service
    - ingress

  # On passe les paramètres du provider Pi-hole via extraArgs
  extraArgs:
    - --pihole-server=http://192.168.1.106
    - --pihole-tls-skip-verify
    # pas besoin de mot de passe → ne pas ajouter --pihole-password

  serviceAccount:
    create: true
    name: external-dns

  rbac:
    create: true
