external-dns:
  provider: pihole

  logLevel: debug
  policy: sync
  registry: txt
  txtOwnerId: "k8s"
  interval: "1m"

  sources:
    - service
    - ingress

  # On passe les paramètres du provider Pi-hole via extraArgs
  extraArgs:
    - --pihole-server=http://192.168.1.106
    - --pihole-tls-skip-verify=true
    # pas besoin de mot de passe → ne pas ajouter --pihole-password

  serviceAccount:
    create: true
    name: external-dns

  rbac:
    create: true
