apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-metallb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-metallb
  template:
    metadata:
      labels:
        app: nginx-metallb
    spec:
      containers:
      - name: nginx-metallb
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: nginx-metallb-html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-metallb-service
  annotations:
    metallb.io/address-pool: first-pool
    metallb.io/loadBalancerIPs: 192.168.1.250
spec:
  selector:
    app: nginx-metallb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-metallb-html
data:
  index.html: |
    <h1>hello Metallb</h1>
---
