---
apiVersion: v1
kind: Service
metadata:
  name: nginx-metallb-service
  annotations:
    metallb.io/address-pool: first-pool
    metallb.io/loadBalancerIPs: 192.168.1.252
    # external-dns.alpha.kubernetes.io/hostname: "nginx-external.fabsys.ovh"
    # external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  selector:
    app: nginx-metallb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer