{{- if .Values.t5810.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: restic-config
  namespace: mon-app
type: Opaque
stringData:
  # Choisis un mot de passe fort et GARDE-LE PRÉCIEUSEMENT
  RESTIC_PASSWORD: "ton-mot-de-passe-super-securise-t5810"
{{- end }}