---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ddclient-config
  namespace: ddclient
spec:
  encryptedData:
    ddclient.conf: AgCauIWqpn1/0UhYEGLyrVH9R7IjKA8tUl0OzxH4G4Ia7DA5vtf229m8TxLo8sNPIeCK0JevgXlgR7YX6Nm9BHFiyxootE8LLB4JRrN2rYjZCghys9NNO/e6ez69kwdCUFbJv9gNsx7swxFtiHHj3AKeKPajWyfsvBaNfXHYsRrrOfqENB1GI51ihDuRF9aBGN1NofQ+MSPkt7JD93WXoc+yKKYlfTTb/53U11UbfCBqkbbWLLnZitIy6nBBOzDlg9qTpFynuAbkv0bb64eiF+/KsskJ9zBaXLbO5kMW64bDa3ZssVasABZEe8XcnNSQRlowghTpp4obZfjflurpX9KKPX8BNmj6v9JqKVL56EuuKtZSSp49GKpeO/ySyYmXsoY5d/E944QUWQk8IerAI5eSBX7aXkhbe4c9J6AplbAcT/fPP0pO3Av1BxyNglprRQbsvZOc77GzUqYDxjKZ5/Da4/NKYq8Pm66Iza9rLUsFEo6qbT8eZPrHDhJTWSK3tzY1a9qzPz3Mh4zJDLZYf00v/WDhMzZkns0z1yJPFQ82StC3IILXFHEtoYCPNlZhS60dmz3Wh1rrOn5OYoL2cIU+HxzzxkCZzi3fBWoAxD+hfIXS2PhBDbFWwL9BVDFQYwHOnaoQI5RlhmPiHgf4gPA1fKE0VwNAqpf0J2On0C2d5imNUzofUx0hGy8Y7BnTHNdu+gpAveuFvqKbtkOGXVuXDpWc4Rm5d/rlORPE0ev7q46R8ZMw1dhpwZWqiSXXhAsq5BwVbdGvtIJ1anJQbiwrm5wnJrPJ6PCARfETIrHOzK2eHJu4fiB2KoyR5Hjx1EUiP7gqlhNdGbkDUwH1jura7ufLIi0R+IhfNKoD6svKb1POiGmSWNNilUqoZMI98Sw7laYQBQtpsyih3LlO0WefQ2QGHyHJRJeTRz47212eJNSQbs9getDR3f6QEnx//b46P7r9ELzHdCOYW8RIxlurJ4B1YvyGQn4ZiNdpl+FUYqwsfr4huD3ONzRUTvi1ZWhMqIBrQfXbRU23JWj/bSuwpoY/UAbhAwFNkYELS+DiKXvIVGvOL31mXn87+Xucp4aM5gxjbb6dBjabzxhR
  template:
    metadata:
      name: ddclient-config
      namespace: ddclient
