---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddclient-config
  namespace: ddclient
spec:
  encryptedData:
    ddclient.conf: AgBpmCFI7UiBZsXnQNEuFZ9m2moPLB40/yiEdoel7xkMY6fkjf4BfNXbpwKHwMDbsKpseKKVF8i6013gJcnrwOT2oH+AOsDx5vEz6fXrFpzHwuN8ar+c31MPwarS3Xsggr+bsoioKu9xxs3OdJx/pQG8UajRu/moYuwTi9HhWQ6HtMo8YmB/MKasLmrFlcjEmk3Fr7Dc236ymuJmwJL5PH7WdWAIcFSAHnisvzdxm+DSZgei7Ewht3i0/sB0Bv/1bnODGPtOm5Bu+72vvfGlNmbrtmk0IjwpdqmSyGOb0mAqvY0CLsaNS6l12v3a4xaVFB4jydG3wey+c0wWSD1aZuwxwOaLS0mW10MnUjMzZ0ZDbE04+WgZc8D7gg17ytq+UW0IbVkxbun5oeqNrbivA62dQdJSE+Sl8hOpjhU1+ozyEALG9G3J5knpYFWA4+7PAsR1CpMV7HjYoS1IEaTJ8v8oLdCZW6BNUBjDlYl2LEDDSnlODKeW9WP3nNdmB+wl8+nEiPe4gEpXhWrW5PqYcNv0wmOLuxo5GI3WYpkZp5JALdDTyIrW2Wnph9DiIubag46Eirxd4Bkgl2638d3N2V/uywlBXVxkEO7u1bctTUdYmqEHfML7DNiTYm7FAG0QEkjIyQjHGwJgPaw9o+3tL0oxtt3EaSCrTIcQuE0Au0nriWb3ea8L+t8sc4WkJwmWK3ZIB3CngWc6XfMNi1Yeg2g2J8fvxpvTOLo/Oz7Ri29D+rR8PgNzCM7K2wK8pqoabOa/K7GCTEmbcXrD9Jjl+xbv0KWp4YfmK1VTaNABwxioAPTBczr+WkGhosvQZu3KEsVCFtRJJlHmucV6uVVT4n5OVl8YvI1fV5w81RtPF2P1BQVQ+e1dlURPPwYEhuGHQLcRUS36DP11OT++YZnECg==
  template:
    metadata:
      creationTimestamp: null
      name: ddclient-config
      namespace: ddclient
