---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddclient-config
  namespace: ddclient
spec:
  encryptedData:
    ddclient.conf: AgCbXsVOtG7RUJfttHmP+1nJf9JIGpOfZJF1JGH3yvoS1xg94NqNaMTUeayF8MUIyss46FFBDnGYC/Eoi3TLruBayi6XhmjgrmG4d6dHnbKAbidktm6JGF4WTSkIp6vh8qOhjKCLwMYBqfVvfhvpvtSBymSOYBtw96MsaEpUx4OupIxBYRUpOe+/Dj5Cd9X9n96OAWluQz+Edx6yxz3BU9xyw9BJT3I381OFrtJHmX+vHITjvK3WaJ72VlgoUumBrtp6E1wHZbdVfc0g2fEczjswRmYTimmFbJk8pNcKieIU3OoIPLAq2ACDwQT87Oe1xfvnJtwufNOYIVmIgno+EX5dhT+gwBaE6THYJy2zuaveuNlYmb6OB7LihA1zPouDmD28SKMK1Zv1U5C8ABHF6YGkDBUmPY3YyM6BUmB2hHPB3PzqF+H4FSHPDars740U8evR8mLll7+eeQpNgQ8gso6VVq/wmwtM3U+76gjK38br1UHxMsrYASzrLXeajMUMvdaD3UeqErsCNSISXPtlue/zfRUbbiENssDQ5iW9/xOOaw3yi2P73GoIBDYfHYVFBTfX98y69N4Tc/b6+HkWzPKAA4KnzEbMw39B6bo0IlFP1/aUjzQTdgljeCkC4moE+H6fMp/s18OiounCoTp41YppLSZMrm8fVhgEL5/qb1cBqFbEcOAAqsNBtFOq4H29crWjH2PZHldkG20bohKYDFePEKuf2a1HUXPsWpqvhT55Rup4kzD9IlaqNKAyxeQ+S4fwKxwxJUEPtBk/kYmmW9BAHYqPxM8YVr2m7eEWDzkZwOTa10C1e0uQXMGrP6rtzoWLUlhIunamNljxBl2jz959ztDnhIpQ08Osb2hHBVrtfovK6DQtO0X9ew==
  template:
    metadata:
      creationTimestamp: null
      name: ddclient-config
      namespace: ddclient
