# aws_access_key_id = keyID (Backblaze)
# aws_secret_access_key = applicationKey (Backblaze)

# base 64 secret :
# [default]
# aws_access_key_id=TON_ACCESS_KEY
# aws_secret_access_key=TON_SECRET_KEY

# echo -e "[default]\naws_access_key_id=TON_ACCESS_KEY\naws_secret_access_key=TON_SECRET_KEY" | base64 -w 0

# kubeseal -f credental_velero.yaml -w sealed.yaml -n velero

# apiVersion: v1
# kind: Secret
# metadata:
#   name: cloud-credentials
#   namespace: velero
# type: Opaque
# data:
#   cloud: <base64 de ton fichier credentials AWS>


---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgCreU6DB0M28AwT04pxWbfr6NvSBuyLVCo4uPlDO7rfDveKIl91+9+gMz4KHDxccSJtaPXoP9a4kFZnPdSRXiGfGzt0V1NCSr9CPkyXEhkG2cOsZx5qCvNME9cUlCuUtp7q21b2YjXeXHCdzFXmEnXT7LVh+yYNtLAUXVOojZlAQ30c1IjMYwFILmbQabfuQ04BaShNToZhp7MY3WIODDStdiVr47RHcSihZp0xkPmXu6a2vf0Ei+PX0PzKqPv/FSkkI3vDZ5dnXP3pcfHieK4KAFdD09M8TWzee0h6JVzbllGNmi+JKF9NN70XzjIHoAZGSQlxjpD1Ve3Pi4HfaiDd9VGdU2DShaG/HK4zkCYLaO/rwscPIICwLO7pBjkmXTovqsvultVwweTrR12rWYOCeOhiXWaU/U7yq8aJE3VOtr8kbN7Sb3g/3LmTyzu4BF5+IT486tFS2MBee69cQ/AuPrbHq/MPj/JjX7wvNLHeDGWVz39Xrlnn4d8l1ZnHK1ekiqlaCwk1Z48/ClYrFhPgsejJRyJzfbppdiwezJWIqs/fVMAb3eP5q/Sb5CDat0ugtTcgJG5HBr3bWPb+Azy3OCSW7f1UNj+0IPXnQQRPG8dPA7xanml0qZwhurROogCY1O8hEIjHW1Fn3u9L8yefiS74wSaiAMBaqEPNCjKxuDcUVloM1lm8y3W3ujCEIMd0NQ4QKo/+ufdm8X5SzC6boVy0LcK7tCd5vI15MrMnBg1PqwHmFsMBJ/76MG3NU2HPGKKdjhCuxpLlgwDKaHbPWafdBGtz+LF8FCBqCNqn8bgwW1eUyYjFvdkw007qUHRht6pcSfTmwhB9OcQ=
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: velero
    type: Opaque
