---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    apiKey: AgC0GFw0TN24dtAy0r7do97xqU0Fje4GAl1kn5FyZG6cON5A/YZqqVGUWLxSj4l8vsMHDZoeS9ZMGt8Arp/hmI53V5npUVi9HOasMVEdYYbn6SiXD0yhTxxOG6NoV1+a2VRLmN9dLPCV78gP4AKWM1Vt7s2RaxIrRvjhWjDYG9mCoMr03Jqri7nm/2XAW3pEcPWxKfMBCLrw7eXBym6uYBrpJ69LocIGw0HK9Zddw9J6Zffb17G0HdlOomxfMrm/5mw/LJYYCZnNE9yY+LIG68wYyWx0yLzOWB7sVsdctCBBPRUE4wQe+Q8nCFuo0Szyu2nuc0tMK5/3620kz3zzFwKUHg5cM2VDdpaD4s/eOltwcS8/ncxXC3AH6zTrtGAhrdpCzGHZGO5t/FoViOVs2m8zSnMlIynHDKUTD0qfpJE4w3qMeTXIAivdPxEax3IyJXSI0BE3GKmyb1jnPbJmqOM8q92gZM3CrTxg1f3A/3Rv2zYoa//pkMqWxgaWt4Mu5Fr9swhRMM5vz1zG1BcsFN+dMkadpvrTbwKNTUFywOZO0s+zhUXIrOOjmAMrQlsD9bbH50KPQrkK9Dm59DuyBPVYEySPl6Tc1vnrqsQrZbUYKkq3AgGOMHLZptOJ9BfKOAJFysrT3qUkFRgb40ooJ0Iq+sNkpdy4Xw1U/BYAKnnVFz1xl1D6EqiPcOsQIkHffErJ3QQzSUlY1vUOaXQ3taYo09w3cLcFqZGS89S40rnwpXXzN3UcPNtE
  template:
    metadata:
      name: cloudflare-api-key
      namespace: external-dns
