---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-secret
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgAQKS0Jryt6F//ovRAFlbGY4xwCFmJ4SSA68CCzQYb2FrgReCXzWfRwBkxscE2Toy/62/tTNViCfIgFJcw5RMx4HbM4YB8u8KPdMS2FCp3GDUqJL5zc8IqtlE+d5GIr9Xelr2ntY27AbSZdbct8ECQkFB0NohLDYK4jy3U7cJHxeIvpTWP7FKiin6xLXmJkJ8gds7HvqLCPgD9jtRnyJ7nwjfZw8T2wLFkha4Lx6NFzsWIeWgkKPaEnR6AWydrJdbKA6gp2xvuir6cG9X5aQt9UmRMxLywjugkx+uW6Ak1r/xugHiy83rUzAjtEFXQSXuNS5gYFdfq9QGkopvTPV+RwSOOJLwpkvMHzUCvhuwuHe184qjni+RGBDxgzy+UfC54vOVuh1y449TPLJdrpR24oHtu4Q6qhTRx3JaNiGjKAnyU7yYgkQOsWiUthsqCt/2nCtXn0g9HrwqKjuQH5hZa3V1F72dolzrn0/azb/BxO6r0ZqSrMQHiv1c2dUoMP42Eg15CiNoQWxfOryVUBAPIBlFKyt9gUtd5eX2FmrhHixthQzyypiv9gWKasJNrj3C8AOBESh7qNNTAtEhneye47eqa6bmGgEXsbeLC3oDo1lS+McmwVH+sTfIcl2bkVbG70iXjTP0hTbGFDggjFC8y7k/n3djOGQEK45WtZcnnmx7nsCwXm1T6jWkfDgpatRdjD2xD3hh4PnFvPMVGLTJENSgjwvtjlG23agGbku66HF+6XQ8s7apDP
  template:
    metadata:
      name: renovate-secret
      namespace: renovate