apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nginx-html
  namespace: nginx-demo
spec:
  encryptedData:
    index.html: AgCcNoiHqke+SvFUWKCy+ENlaF4LG6OK25kDzrKQvnVT85mm7AJq8jDj1hevQ65MYIZZSAX12m8wvJ5zX21xjpbJmFK8WqiMFFQugw3R97AuHmGn0SpXl6EAUD/+nPsXtrexoQbOkxOLuJ4ef9YHecebw1AKQa0aKNEyPHAL1geAgUB4CinccxHax38jw3HazBwuSLSQ48Vtb+DkdSR8WhtekxFt2weg8e9A2QY5DUlsVs3gpTM06LS0uJBbP17h2mL46QsOadPtBAo9b8rmlyZLQlMTj+cUYIqOL+whsTwP39n7Y/W902r+Rsd8MKzkxs4uypcQkeIB1QlXXwjzW/ym6taMm+0EM+LK11zcHMw68G/P/BPFw10slLRAsEJ/MQYA5U5xvsdiizCoi/qrCI3MGiE6mkUS7vTYEeQhlVxQbf2eAEqYm4cLD/Xah67PxBqIh2T8vzPF9fPePMX1lnVphETeGvRwnwuIuw09FB2tIXsN34ISFuYD+XGayDcUM6EnH3oFUpTUzNRH1RSbGqEhqDK6zrcnP0pMgBB7m44scErSgZyKr8hKxXBDDaLbytMC0rIhKsiU93ToXy7TpwC9GFkPRYv7e+WY/5LvF2T60K8iSgi8O1j/UyiYGtfkh3oCkiG8EC8c3pTWdw3Ib0t3LnA7Wl+nqWNImK2hFPorGD45bGD2JOOCoheHdZccEEnafWqqo8Y6kXCC4hHbiFXp3KjM4UNSJeP3nX90jea4kLc9+QA=
  template:
    metadata:
      creationTimestamp: null
      name: nginx-html
      namespace: nginx-demo
    type: Opaque