---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: restic-secret
  namespace: arr-stack
spec:
  encryptedData:
    RESTIC_PASSWORD: AgCyRIff/mD1ykU4bZ3inm43gpwUqxm2G4KJn4VTEaNolSVRtPlxrJoiQcVqd5C1KUEpnQCJgZD2vemmtTt8bXj3JX5RrwYq4o5a0oSOrcMbQNsheX3u0O5CJNi9X3qjtKngPTX4iFI/3zxfbGm6aABpRwUeWoVn6apfjqquvaxC00LxsVAmnQL18JBRHzh2k8CLnms3y8QPazRFr3/wnfMv5gMJNLW3ZKv8VFIQNqoT1GfoqLeP0mndEoO4ZzM6HSHf6xC+5FtAyTngVhJcXzy9VNwRuomgtshWmFB0FH9xkYsY6aqjx1O+6tuFQY4t+mYfXhCPr46K/nbzDRjbl/YL3ftgbPKh2MlcJrq/MrCsF76hUUT4bb9J8fT+MFR6a/00kPtSUP+77mgWlhgLlLQgxhxILERqGvpFQc4Q4L4drjKmP3NmLXC41yk+9yQDzc95yJbzI3vSbEuaZip6tgve/W0STEIpAZ0GLjufBjYc025/r56Pvcu3LsBM2xXpr2dP0tXfNlZxrr/IuJOxkxjCcfByX2gtbKpQOreCjORXr1Epmqef/rA79Sdyhc6gDkW2SJOwenFY7g4qmLTnyxrHhbfkg0KlvOu5wlvKBTrIC081Av4A9okPppz2OAW17UkrYZD10O/ZsKtfzfFthvYcrdpUdZu3BBWnR9AORHpnCrBunkY64df3WkXPgPXgqc7GBBg7TkHodpw800r1dByuHsZqdpJYUiM7f3KrjB+qb0YrPfJo7WIO
  template:
    metadata:
      name: restic-secret
      namespace: arr-stack


  # kubectl create secret generic restic-secret \
  #   --from-literal=RESTIC_PASSWORD="${RESTIC_PASS_ARR}" \
  #   -n arr-stack --dry-run=client -o yaml \
  # | kubeseal --cert sealed-secrets-fixed-key.pem -o yaml \
  # > cluster/apps/arr-stack/backup-restic-secret.yaml