apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: restic-secret
  namespace: arr-stack
spec:
  encryptedData:
    RESTIC_PASSWORD: AgBiQyjBnEscRL3ybSNiMtfgz+8AyMjzBzUJirEBbycT5pIaAIIjRdB9W0/ecZgWHYQ5aNAI2RZovZG93KC09ib4yjxlo+q/dHf5HfaAFXErkEWSJG29A/aFWHU7bIsL5XU8YzhwltbZxFxcpzqfNuO95sdmkS3WKlDYTMjHCoFaP3W+bgMEKG1PJJSB9KfrQdzIiz4P3SmdladXVHHnOmsxAWkAPUF9ZUDJzLq4pYZw79I+LLSvcCgQ8veu9wy5ns/uTNlM/DpFZiMx95Go+KyYE4mh5WooAaUNNut8eXGqUrvTFIqJXvXYFQeZI75FuyDKq3qkN4GbxLHyx19zcMPQjn/RCnqRyz78sHgS/pT5C5PA93cgQa36c98hAGdND0MgLce4fJoBMkmvLCBUWepRps0Chw6UuKQbjEGMwUHN075ztDpvxRLJRHYxq1+cYf6BpuGyEt81b6fAhB6G8tINs7mKo4V5Vetd3sNYehwQTuTnXjscTrexDuEn+iKZcslfneaat19hPR1naA4JwvoHGKgTmuDPbj5iGTMSzw27fzzcDoH9fsUKsvDCwinledoFT5Ltt+cM8s2QWk0HIeQgpiQgiuTRtDid0Ic0Q4GHzC+8RIFD8PSYwZToNfsSf4VjWJ1bx9xivNnBt+u2mhJOPdJ1lzpm5ePBjmNe0LDQ0HNTJfNoFz2y4NyI9VSy7snhC2yilXI/khaN9Rnj3C08rotCcu+k3nrQWdvy2fOx6a6jTC+JxBwy
  template:
    metadata:
      creationTimestamp: null
      name: restic-secret
      namespace: arr-stack