---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrent-auth
  namespace: arr-stack
spec:
  encryptedData:
    password: AgBW+nnaWfrUQ9whUpRqCn7xO2qYmvn8AzHY/pgayzWjfC39IK8u1Ppx3TISFmWH6yQyRKhe9kmTCLvku1aTsGr2c5QpTqY4o0JNUsrBJw3C8MSt8ZQJvi2wM1Z+jCyO5CL3+L1cP7GcFmx+Q2rS8btpvCQ0G8nVQ1+om8CksGOgqSZkgNGr5h/nwFOmN6YHN0+ITGxghjEMwr2CyoR4m984Mo47HWemOszZ6yl1ON54vuEaf5Pu5IEim/AHaY4sJOAmLkpQcg700EYEkI1QQSQZmmw4tVJQ/C3ccwkYxRoww56pDNNADzh4q2tn87ZI7bRGhzjsd1JP+Ye29Ra55f0BCUBp33Tb0/C0585zc/WVidE5wgl3n3xheSSIXoAWlR61yBdR2R8EUWqxPfQKd26AVZn3EWiLZE52Pit45M+yWvj1lhQnBOVFw485qS/pjPWSLkvhsrIiKqV/2u0KiQXxIEpGbNLbW6Du1nXBlinzCg5ytp+xelaUaPlTlAkHuJVRedD9AUmiiA1bo55Cs43/gzHgQhVvOz6Hk6U2pddUxps+1t0dge3hBTBh/x705O6IBZjEymayAaqkSGG282qJY9yv0zUus3NJYekkEBsKXGusQgNhh6cqLdOSh1v5Bk9r1y+BISClCHA4DhWCNDRPvF8bjGVWDkUDbE3oooFV6fS/2a3HSwACDfoNKzahVwUomDiKC7sngmDpJ7era9uCwY/ZxKIJPt5FUJmOZzYoA2CSrerNSRGdzloxe35NCFH6sMuln73/RB6vuREsZ+P0wQhYnNIDPGtInuuaOnaQWIBf/K7ezM4CjQY99OkB9Yte8JvC4JoBHWpdmUVNGGzncSHAj5vCtdDjOi6jIg==
  template:
    metadata:
      name: qbittorrent-auth
      namespace: arr-stack

# kubectl create secret generic qbittorrent-auth \
#   --from-literal=password='LA VALEUR ENCODER DANS LE FICHIER DE CONF' \
#   -n arr-stack --dry-run=client -o yaml \
# | kubeseal -o yaml -n arr-stack