---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrent-auth
  namespace: arr-stack
spec:
  encryptedData:
    password: AgBsCkESgmzhFvyeD4MexoagLZe1h6xTxo9yHF8ELJTQ19sLDtj/0F4Qlh4UgE4wGw/mkewi8kKcZa/8904ZCBexXQ/ISzfwsWTiR0ZKmDTkRpm47zl5pbxWb8+uW4L2rS7J3Avr3yLte6ZkPU4vq1aaB9RD1/ok/sEKuSsA8BGerSzgzQ6qy+qV8piooE+nenrpQUcD6wZSBODX4Ri0n4IWaGtpcfl6WnASuzuE/IPI+xP1yp9BolbvXTq7bsLK9uKgKEGBzvYOxQdSQ+wlw6ldddKqce5SinT4b8QEqLGh0POWrxo9SvVzFgFxcgd/gTh0g6sFkis/cnf873xjgPCmC7GtaTzj4OYgebxNt1J2c3YJhbWibQloHHJllMs7oMJbya26yQha6kxwvgbE4FTncGBOum7Mp10ZhbfM0Vc5RRaiqxNlXsjl52TzsyKnhPam7rH/t2tORVImY+4BtEFjeu8Fze04GQhszasGwCF6SlswZoXxwyg+vEjhwDaIKZYFZ/XnJjq7OTJS6yDj347olahlpoEPlaA+V4HIKQ/i3sjE05bAzdERo5GogC/23S7dmlNoWQh+AK/1T/Woo8u4gFn6M9UHE2AtpP6U2f6u6pQvf9QqKV52RJxbwP/+FoSh1J+Xp4q2wgCGoUfbHVHxcswoJHd2FlV6EtlvPSb4J/y7G5n7baZ6dAhUPyDbX05d4C8krpLIG1pYsJelp43od/R3b+7l8M77+yWEOVjHGMucLIMyi/hxWlRlzd7mhPG24S/gkki7acODZ1kKUDK7D8OgIfJSF6YnqRcDSXYgx6FmMEpxwMBXlG/V51Nh3yVwT3xVqJAQKUpN88Rt9gjETP3LuQm8J1OJSY/tKtD+eSA+RPkFTQUn+4TiRvpntixhcrAS1bH8
  template:
    metadata:
      name: qbittorrent-auth
      namespace: arr-stack

# kubectl create secret generic qbittorrent-auth \
#   --from-literal=password='LA VALEUR ENCODER DANS LE FICHIER DE CONF' \
#   -n arr-stack --dry-run=client -o yaml \
# | kubeseal -o yaml -n arr-stack