---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: shadowsocks-config
  namespace: arr-stack
spec:
  encryptedData:
    password: AgBm0OglXToz0mjW2rgwp7mIRKM1F87staweFdNpiHXErf5AQ8+ouIdwhz4J5v11xe/bpLYmHl3U4znTRz5QO1HDor8BAv5SiEDa/aUHLJdDgwxCjwdBbjj8peSI20Sdf2WbvQIXQcvFJJO/jErFCgKVxfUeB5Q0eUEktvs1mVRWYxFzOgq+dme5+hMs9SJ8crwz86fjKa1bpImjg23S+lyrM6wjld9TGC56YkitIKb1WE16vTntLM+ZxGCNZ+LmNmXf+5lo46vRDMdVYjRbkhnIarGl0j2t9fisu+Q0avC1/q7BsvMmszz+iSuZpvXlzTCjJ8eph0MWy1+kI/7NnVT+v1A4BgunEiSmBGO0oR9SBR1XMhqfXSt/4RAxXpuey5p5CiUx6UfIujN/LhrQvp/5LPPoNDn4alR0yP4ggao8FZdIhuglLKiKRckBwHRxF6/9AcJWVnrNeR4LHDmDfeGpnIHqrimk8KwXoIAXALaiyviyKjUpIDrH67d28ac3D4aDLcxIt4D8uylhZaAPfMr3cSaLZbpQUE/iZoGqjz7vb0riydaUp8ooLCvWrLrJP/x86eTghU691aWXaYnDONWer54pkXFRWzPHgIhDeFAwejyiTP+BstK8JaP5RJYO+ggseAzpPLNTZdkreh1uE8pmnYjSqi4v4Q019b+WZQa50+VoT5jtkK60RcKvdm7dnlGBVQCquZg=
  template:
    metadata:
      name: shadowsocks-config
      namespace: arr-stack



  # kubectl create secret generic shadowsocks-config \
  #   --from-literal=password="${SS_PASS}" \
  #   -n arr-stack --dry-run=client -o yaml \
  # | kubeseal -o yaml -n arr-stack \
  # > cluster/apps/arr-stack/shadowsocks-secret.yaml