apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shadowsocks-config
  namespace: arr-stack
spec:
  encryptedData:
    password: AgCnUH4c8QLE8GynZ2j/LH3AlLWtlBRitLMPcVoc8g0Jy9UFnnSzNBWppRrU3ju4x6V6dJZQxaaTcEATVRQbdXRw9sIOPN8M3PEtlk/EMCPzkhsNeKPsA8MWRLO6/tMq637qCCOWvse5ds4v1FKHQUpgkqTHd0lFRBgkU8tlJCbx/5nqqrw1Y27hw3iI9D4Q5a2pqpjfJHrF6IPk+Dpq5E+dDLVUq4zs5V+z9lfwwSde4LGdcw1racNm9IZvQ3j5ZSli4F/GNCGR6NE5xzyPIM5dFIJP9X2+k+iiVAyeaUrhnOEPiBTsDbIo6BIFgxmK6und5Vl8yNFwH12+BcHffPzFhyFVpewVBsHW0J7S5ewNhTPCTx6rnsVzf5n29ZCQnDhmyKWPsF5FyimeKRUF9pXZGrEN/iGa6JSLbdeZH4cw6CSHN9HYzXzzifh5phTYNSi37VTcXwZYe+fi8ahfkA9jNkNvB9Q6TGE0gOdUfb9RjkKvyObE0X9vGFtLAEls7cXeX539WEsqpD4rC8OENKYjpJ9ke4Qh09UOrRp6qWj3hf6TKF9mw+CPbz7h3iXhrNWJbnq41MTG+DZMF9gk5hZzn304U1tA7XbjXFSowtQuwx1KJ32W17leiS9KSy2pyQv9oZCrWjc6LjEeiSw3k9tFUIDJI4aOuKLAE86tE8XMrHYPcyFJN3aiiCBptYG8tDFwhjExqkU=
  template:
    metadata:
      creationTimestamp: null
      name: shadowsocks-config
      namespace: arr-stack



  # kubectl create secret generic shadowsocks-config \
  #   --from-literal=password="${SS_PASS}" \
  #   -n arr-stack --dry-run=client -o yaml \
  # | kubeseal -o yaml -n arr-stack \
  # > cluster/apps/arr-stack/shadowsocks-secret.yaml