---
- name: Ajout du repo Helm Cilium
  shell: helm repo add cilium https://helm.cilium.io/ && helm repo update
  changed_when: false

- name: Installation de Cilium
  shell: |
    helm upgrade --install cilium cilium/cilium \
      --version {{ cilium_version }} \
      --namespace kube-system \
      --set operator.replicas=1 \
      --set ipam.mode=kubernetes \
      --set kubeProxyReplacement=false \
      --set k8sServiceHost=127.0.0.1 \
      --set k8sServicePort=6443
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Attente que Cilium soit prêt
  shell: |
    kubectl -n kube-system rollout status daemonset/cilium --timeout=300s
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  retries: 5
  delay: 15
  register: result
  until: result.rc == 0

- name: Attente que le nœud soit Ready
  shell: |
    kubectl wait node --all --for=condition=Ready --timeout=300s
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  retries: 10
  delay: 15
  register: result
  until: result.rc == 0
