apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-config
data:
  PAPERLESS_REDIS: "redis://paperless-redis:6379"
  PAPERLESS_DBHOST: "paperless-postgres"
  PAPERLESS_DBNAME: "paperlessdb"
  PAPERLESS_DBUSER: "paperless"
  PAPERLESS_URL: "http://paperless.services.k8s"
  PAPERLESS_TIME_ZONE: "Europe/Paris"
  PAPERLESS_OCR_LANGUAGE: "fra+eng"
  PAPERLESS_ADMIN_USER: "admin"
  PAPERLESS_ADMIN_MAIL: "admin@local.home"
  PAPERLESS_OCR_MODE: "skip"
  PAPERLESS_CONSUMER_DELETE_DUPLICATES: "true"
  PAPERLESS_TASK_WORKERS: "2"
  PAPERLESS_THREADS_PER_WORKER: "1"
