---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone-config
  namespace: paperless
spec:
  encryptedData:
    rclone.conf: AgAKz6v86ptlkxCo06U7+EccIXCKvZHwu5UUaX1A84MAGIoKMRvH9oe543AWVRCutNZ9ZAKw7sjGoJPxFj+aFqUNuxdWPmZ88Dp4pFXn/UYHMajvr8CZZV+VxF/bOtE+zAzDFQaeL2Q/7lWXNOESGrVGY4Ki9uX9lv9xxHEvXhJDRdHZ4GkwJ6GXZyufbr86oqiuxE/kfe5e8W7Yznh+CkEQ8v/yEr9TL45+tMNTO7KZ0cauLYGtrSLF3dq/7RsIniGNR897MmEzt5ca77e3nlx4amyrsrQeyrQSSVfB1TNKJp9A1T84srE2M7WU4XuQGS18bK7WvzCpkP4Fn//cKolQgJ7a766xR7kSWYInlho+s9p+XRi7aHn5rGLS3wZitfp2yqe6VGghBgh2qXiRjWVH/Zklqexu11PMAWYMzzLvC0+lsm2hOni24UWpO55nBDGpiwWDgAEX+7VItqFS8dmHNbEuB0oa6H/EiUaKHUOhYOiHJUD1MNVrt8UcZocHyHXcLyR2t4PaJ7WlU97+EQG4hlyk5yHdYmxhiybtwjoTU942UpaVttQhzNtzBsA3RO4iLuv64VAm/Yk7yxm23JIb1BNsHgxw+AwFzP5M/IN0n+pqqHBhHEzMCyHBnB+158Yfs1X4m2OS9ZbdywP717wS7McGmdXgiG9nvsHpQy3G84mG7ZZOBpCSXXODlUHxzyO6yKAsFpmIfwEpzQCg2LzzUZyoPxsclh1m0cK1nF3AVUJ8OBYnE7sQ8H2pqxzT1zTmvO5RPDpm/IT+Wdt4ybUYtRrzWcIt8PMVvUvSCq9wAAUr5Goc/HO1me1mub8yOBQDpdpPqVkkW4wc2Mv2p09nmwrJGiCijOXItkyu/R0uFOoQfpLMj7yARxienI8vhFZd0BfsXnrI8anNP2B82V3TvmCk0aeiBDMrV5vQmWRTLnqfsHLNPylP53QUQS/pzc3CbVJhYjam6Zq7VcYGpELx5O3FuqVrz9/T3nI+escB1Uu4uw2T5Ic07BLZoND69ZTq/UBdGS0a/7kNFrQDC1IvDA9vu475sWZ4FxxDyrPgtFTmFV0YlodCR56joWFBKBR459paGmWiD0cDpFnH3J5wH0aRN/LsumMu/ktX0RH33wellmVQs7dSNFET83N62BQ8zMNL0zfvvPt6zcSNqFz74q/EQeSNtd59ZfethBnW5fGnpEclw9+4xo9p4R87H4n4g84/9OFaQ0OjZfBJ6RU/eWd1rCvLLy293MTLwCpKTnoayh+kVQxc8GZRm1f1ZIWAKb9EzAxRepDcfz19hruTOOwADtE2b7ik+e1PUx764G46Ai53XQ5vMiQu6EoIiLs3IEwFX2Eof8Q9zXEMaYONvElfP5R3IN0bNg8vREQKBQg+t1VIysB82e/mKaiZo5xM4Ig42LBsbCs6aplIgoTI3+BRlKqD8lObAPcZErdBJw5QFXSiXSoZj2XXVQBkt1wnghta3UE3lEnyzmgZYeSKTK396kgh8MSck4IzyysDgFCG4Xyd9qNY3SIPNKhQfjtNyJBtDCKdjm7bJ1i4vtt9h0USlYy532esjsPtHDfjP6icf86l
  template:
    metadata:
      name: rclone-config
      namespace: paperless


  # kubectl create secret generic rclone-config \
  #   --from-file=rclone.conf=rclone.conf \
  #   -n paperless --dry-run=client -o yaml \
  # | kubeseal --cert sealed-secrets-fixed-key.pem -o yaml \
  # > cluster/apps/paperless/rclone-secret.yaml