---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: restic-secret
  namespace: paperless
spec:
  encryptedData:
    RESTIC_PASSWORD: AgBxZOxW3r1/O5dPYWyOleJWZgnoC1+vQcCfsZ4Ca3uXdbFMaoN0uXpaj4iG5FAfcINkJKjL4EUapGJ2FvO+1KefDeIPer9b1CySW5lwU+gZinFDcU34Ir0QXjBpeG4n5F9YYfbZtu11uwvIT3kYjPY/FeuEDaDpr6NWZHVr2gxHXUarzi3F7WW39qaxiNqAerK0QsXUnEevnIkrXBMoEs2mQJfCz5pKU5+2j9YneMtQK35OzXc7E/f/l1gpYyie1waCCvkplKeRLLvrKymAubyZdssqYpAh6D3/9bTFsu9BSR9wMMqk6i08ZTsfGnHW6sJJj5ESYngr2zqw4x0R5rovgBfTSoVmi0qTRqjyQBv9KfTn2lXZkq1WNfLXRYZkbq2OHRB+LJ/6VKHiFbPyMjaoosksX+Efgf2V/wn3J4xgIkOZMce7CnJ6YBDbz1MbYWWNiVEg5Tp3fTXeEOK0HY9EvgdGES2X/+1YcG1p6JF9pAIJVGg5c8aOe3CX1HP9kvVi+suCi+a/yldkOregPWTIlW0i3TEDYJsivHOcbTtlCixIFAlJLLJqMms2MzTUJKSHfotnAWDvOEliN9DP8HyFu3GQJreq8oxMl68Nq8lEqCmZqjOM+GsBtJqNeibx/OKlFiKdz30Ju+6Sm41QRYKQ+Tr10hMMgqJnUa+XUlHz0SB9tSSxPzULw9VqntKYhsm1PhNaQGcRPk4USNZOHavy61GQrI+UJkDhaHdTd08fvABP9BJN7fE2
  template:
    metadata:
      name: restic-secret
      namespace: paperless

  # kubectl create secret generic restic-secret \
  #   --from-literal=RESTIC_PASSWORD="${RESTIC_PASS_PAPERLESS}" \
  #   -n paperless --dry-run=client -o yaml \
  # | kubeseal --cert sealed-secrets-fixed-key.pem -o yaml \
  # > cluster/apps/paperless/restic-secret.yaml