---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: restic-secret
  namespace: paperless
spec:
  encryptedData:
    RESTIC_PASSWORD: AgA4qP8BrYT8lwx+tVtEOHDHA45YoPdLqrck1vjyvitvG7En8QcE+qOuaIRoxpe/+IfwahLCNvIL0W8U9aErZDF4qQ0y81EYIha2udgsaEg++N5GQN+s8RCkRsntj7znu4BAJfUTHnpASj2Kl3CXnUPN20uiA355g2ZHoNR1NMKQaIxFO7glkBbdGHnV81AQ6O9zt47mNl38tslIJp1ZsvP1YdHpQ/6e7uEj1Rj91SHpv2oKcHcfN3PNHZm1j6e/BvPSWNBjZioIi4FMqJ1wEUCQqTLooWGSKu6wkFF6RNVgKJnKkgtJ1kReogXGf5dVzA/EC/JB2S1T9ZUuhmLVJuAs8FspAigQ2Zzng2rmutsNNrVlV6fkGrA6pv/xuNwhBz5n2umSOozWIXqqaif1l4jvUn8yzigvbq1lKYFCLXkiyXNpyiqg9jYpfCDJF6LW/ZJ7pgH6UeR9KG3wZvavF6hfhVPkRd/vKt5rGFrJwrfOQ9yBKNenRpGgR8klInVYtuEZ+zXQ9mpvrpp//j28oQ3jmBwxbQMKpuy6gNaR5OG1Pevh9J9ddGDj43EHTeA7zTjMphGkGAD4suqY1gYxSZWdUNKWx7WZ1eKgIfvAUuKzNsfk9/FxPwgHIJdGvBXpxFM6MCXCL1bhWA5knyHe5bmvRbyjbAfaj4cKhN4/JvtHrfksAx9MXBGTCZWvBq/eLoyTRBa+b8RkONfunlVUCbfdl45VEOfKSpSdwNXvLN+gKImBsUIKYciV
  template:
    metadata:
      creationTimestamp: null
      name: restic-secret
      namespace: paperless