# IMPORTANT : remplacer par un SealedSecret avant de commit dans git
# Commande pour créer le SealedSecret :
#

# kubectl create secret generic paperless-secret \
#   --from-literal=PAPERLESS_DBPASS='TON_MOT_DE_PASSE_DB' \
#   --from-literal=PAPERLESS_SECRET_KEY='UNE_LONGUE_CHAINE_ALEATOIRE_50_CHARS' \
#   --from-literal=PAPERLESS_ADMIN_PASSWORD='TON_MOT_DE_PASSE_ADMIN' \
#   -n paperless --dry-run=client -o yaml | kubeseal -o yaml -n paperless > secret.yaml

#
# Pour générer une SECRET_KEY aléatoire :
#   openssl rand -hex 32

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-secret
  namespace: paperless
spec:
  encryptedData:
    PAPERLESS_ADMIN_PASSWORD: AgB5allHvPiYoZdu8tXi3CpcJp64M/gCC4jteHjBvBbKbLAvpyEDJrTjoNgdToffRokyXJUSnEFN2xm+UhSYiSluDu4Ui4GGgV1O2h5XNOYGOFy5SP6M/MZB2swqpyi2tF9th6KYgf55/y7V+EYJp1DxdtbJmB/xhhM0FhB5sylInM5OS1evJ4T99wa30Sd9lmQ59TMM2aqAzpa2hDS7F0R20iaqC6hlRXkkUKshFGzvuFkB2Of/DlGQ/KZkekKoyLg5Matj6R+3xB6b3/LMKTgidfcytaAhmUJ1ayv6xwQ6xLm9TxYbAKuYpoeOhFsC0Dh+0YtSnroReaDSsCW4hi3HBzv0OqMOFRepoyiTNGNqkCuPjqZR/z5elDxNRCvR8oCBURIrTSiTWwuwuM5SPv5C5NnIQ6K7Ei/M53jC+t+e4dUqzPBfOTeqBZgL2gd4yzrp4uJP2EHSrqK0IQJ1it3kWe3ssnyOvZlABzUrTn52cRMENTPuzdVO1PpiDeIXfw9mtSeMpWYHFEHUlO9VbZetE+4rwexD9oFPDqsXLt9OXnqORFKrT7eFdUR34lForaTxVwKAvd2/9y07Rf5M741E444HsOj/x56FYGhqKkSwjK8Wy54Aoc84/PF0svm90G8YaxHcwp/vSQOCAq0i2+DKOsQG3SX7phwkVZmY8kUoTKoPFQSmiIXj6Va1mPZcg81jUKWDz+lzRinGfsofwA==
    PAPERLESS_DBPASS: AgCJH/w9VwVLkZmzQ0zjxG1EQJkJLdHth/iTFhtT61ekB6O0mUNK6RnlsxJAeLGjdFIebFMHeByJNbcNVO25TINi468G6f9R4DzmmHN6TnRkB3fOhnkpmfbNyQiw1Wj/0Sj2lr2Q1iNsrGXUnCyXIOvt/bZfb34T0qZr0SidSHuTWsJXFiSTAxWnLnfOn0Lms24p7XUgf8iSuNu0JCZcmUjueQPqlUzmewT88Jq0fc4hnAcp0LCNzvwGyF+A3qieYCP30iOqy/SjV+KYHOQNuBFwcaLpFT4RJMyYbUN3JmSXM25ekB/rQgIXheNI7mdYuxfBm2MFx/COpgAgf6kfBLo3DHmqVtrLGrle0+fXIBRM4JJ7j4BbtEaw/JmLjEcVM6k9ZsFJ4l8wjIG5LL/8ssW73bZxhU/BdKaevjsN0UAXUYxHcZfl9SwooB/iClDcDy7XZN6UBmGM3kNJJA99YB8mPnibNYnJd6LbXoeozys9ye2ML0AMNYcpM2qo5ouzneDTzLPw/nUv6284iOVaRDmqYFML3uJH3fW/57egILmgvTP+QMUBc6KoXlJ5Xigt5pweToBiLfsT/+j/LaXeuapkWY/eAenEb+xZyuoUQVd/nsnJ0reS49dVtC6LN12Xs8kXzQ5rg7T3hG4AhWqw3s4xNcwVp2x/QGxEhBsjH5qrn/Eur08NV3suWNwS0y8HdRyulg2HoXGucbuN8OTaD3nTfTO2JM77aBrWgvC20yW6vQ==
    PAPERLESS_SECRET_KEY: AgAszozDQhiX2Jace7YPbdGqvwqzrD1zdINhe8vtbBwcX94coEN4BKGHbJDxgkZNmRYnOTq4xb5abs5h9cSdPFOktAAeW93XhGdN9bTvLjewK5uA9GNHHOWSOIPn9KQZwVf47RuuVe/T59eRlrMf7ieffmBQThXO5s4ubcSuTeYfhzdpsbvw6CKC5xCH8Is5eDkNh5M9mgYoRmzWoa71og8UpfE9I3i0mWi4ZVdvWVG6iynJ6/7rllMyOo6+J87Uq4TA75VHdulwU4+oPX+Ex+Vjsb8ppiEAlBtLN5sXV2ikGDdWy+P8Ir0cFuNA/V1fS+7/OlIPAhvEMtcvvbPJL7aU9fEKs/xNV/fjNu++JdUE0LY2eEaUyJLi8KvsJnZbs+tV+Vg/7x6nzqOG+tRo/NJWv08c1xFvdFsUSzsq6fNke1ebva2zxe8gXR0jwRJLeGNkRcc1F43gkqsneKCAuRlKmNYO9eP/Gl4SR10HmAv0I1/gX+VRIPC2gyA7/PKWbYzMlSmwfQbZbzdpXXSJ9SHqAH2+RNV1hwFes5AdcAo80fJGc4H1jIn8xu6P0vbCahe+gQ5w/06KR4lsDvfuz3SqWVOMDiR4tnlBirpL/CcsmePlXDRHiShHn8GmzO/ke06lDaubR2tapkdzNbHIOk4VBwlRSZ2rn46kmx36hWeT5YSS7y4N6sdN313gH4PKx/edVjdCUo3g7GvEV+DekMT7l7ujNjJHE/PAmeRXItslyHKKE6aE9zbn1MvqzOBAHt/pVIZpb/3tx+LWpbKiIKNx
  template:
    metadata:
      name: paperless-secret
      namespace: paperless
