# IMPORTANT : remplacer par un SealedSecret avant de commit dans git
# Commande pour créer le SealedSecret :
#

# kubectl create secret generic paperless-secret \
#   --from-literal=PAPERLESS_DBPASS='TON_MOT_DE_PASSE_DB' \
#   --from-literal=PAPERLESS_SECRET_KEY='UNE_LONGUE_CHAINE_ALEATOIRE_50_CHARS' \
#   --from-literal=PAPERLESS_ADMIN_PASSWORD='TON_MOT_DE_PASSE_ADMIN' \
#   -n paperless --dry-run=client -o yaml | kubeseal -o yaml -n paperless > secret.yaml

#
# Pour générer une SECRET_KEY aléatoire :
#   openssl rand -hex 32

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: paperless-secret
  namespace: paperless
spec:
  encryptedData:
    PAPERLESS_ADMIN_PASSWORD: AgC+QOndWdlxv7s5bZkXh5pnLyyO7/A6TedbUAtO1euBCaP7ofgxFqj7sV5QEZhM8+Yy9RvXJrc0BZef0MlXDRRuVOwEYPL+CU5vtw9SSRMUJ/m7g74UZ/jUuqCg1Mkxow8W2ZYpqZuf5LXZwBc2ZgCzygCYcrmz3F1hu5zybhK14nFZFrugFHQvHsPCVjkloBZjZUag22Leelj0WYwksKPKGQBNGVhFDRVO/TikLPfyBneWeC4haOlismxUNIuD/IEPCNfQK8SW0QybOeMe5AokgV3Ruim72HI6VJwtmECAM8RfasTNIgPnhk5BwNY/pXTdPf9/j28W8d+WwLaC+7GO2edhA/puqRWazeCSirfPazWJmfImxCeAMfVtNgdAE3DKzNo41ICqeMyROpOj213/gEV7vMMUfngkaMAHwVqNs9QY37/Xn9I+M4HSoFhp4ihZtsK6wZ3CboLhpPLZCO9YO3Mnd5ZeaOtkfw4WvAoMb1TDxvdRw9fKEtHub2NcTcgqlu/7TLY58Qy6rsjzNmo8FpWkNIPBUdnUAG89rezrl5JtSgplH50gW0yGJnbmv6K1bHzM17fLyk+MtMnwTnMqFq/jTad8mN55+D50QikVRoclowI9ZBIxmeUecNKbpoAvUeNT/Jg0N80csHsbUrdIgItOZJFrtC581F5Q1jlNsHNYIUo7bgOEo8WHu/iRsnBId34cw8vYUcFipC0oEw==
    PAPERLESS_DBPASS: AgA27Pk9VnbE9PQDT+ECktG5rB5TN7J5JiCffrwvDFU+y5HpJvG+q6wHuabR9caeBay5I+gvQxqK0gQwi00yMfjHv2ECfYDW/tBnNaECSqZS3Y2ogmhp9qfkGz6wICwGJMUC4KeZw2GQ3Y2bfbmpUeUB0C/WEMOxbRzn1CdML2+EYC0tyf52hnbIKds86VKz0FyovhHb/vJVQmAwXsVQs6txo8TciE6y4yVUc+kiEK1rLpNTCxYJozMkg7XGsC9zItfImB/eWhNWYKi7ixe2KjW1qiicY9o07j0lKBo2EmIEglYn/+fJlTWnmnPoPusCx9nWMOskEmlHiWWYEKxk85s5XmY23DXWmQUrEEzbzs+hs1sB5cVTWz0GA2scmvpCWIaJYlBHhYmm+4UdtDpkSQUT610srsBnErEYQtQX+2YDwJQYiI93NTAdnhtHTz+ETtH3pId8OMMOV8gw1ixP5qT5MZmQyAbvwVHAgQ8z++cmFeS11O0z95bKmgIDILaZDFs/Ckz91VVYeLXVuo3MHvKW69YVVs+6d41+mmlDUs8NXBG6fwQ/ilPUzvQLon+miJq9SUREf2j6nOf5xFfgXuULufxOVjatsUdShit61uJpx4dtDsVm7NFDc4BLhm4p4dNWouNoQimUUhRBEeq0/+TjpzqX7Q4x3ntG5mU43BQdIzqrP8+UcG7/h51cErWJPTod/c7bnObPiWExQxAz
    PAPERLESS_SECRET_KEY: AgCXrAO/NHBvDMW/CbWW9rcNNNPrFsMEf2SrZuChZFL7AwMAZqnmv1C5mIOvMrpyG1XIZDz1i4Gb3mmM+IZliES6JsIfJuAefT70UlzxgZrLfKGFrGg9POz4UdG9k2p6Wgm4wiOZ9ydii4s2LjhGEwFCBGKirzx6by5xTzIOeZ1PwJQbH/lppvKqlGXsHC4qZrh6sx6AB2YgrxdmOPplN85FEgO7yWBIKsUK7mDvCF78vWV8YWIiE09GBuMT9ty7izN3iPwjxt9/gUx31BElHy3UVw4Qfb0MlzH7s4VddMmnkxzZB1xafyx4dVn4sSVi8+t9o6rzRmZ2gPUBocl2CzogSM6njwpoIxr7YLt5KT8NRftx2PU2K9Th/tVBj/zfkS2J893/7cBIYaSaYNnMrwCWU5R3zLrMTs4wVz+mAp4GIdNMbgig9lmLa99PEsmWER89JNezkmKthYbhfAG9RWJvKXQHfkHhd0iSfIGLU62ZFbtPSX8shuueFUIzbdonztrZKe03Z3HZpGX+5fXzCEs3oeQG9JW8lLyUjy31NQig+w3uzvNRR9smZ0QaHZGrkrNsk6Rw5fuH72J9B0NbiEsUP00Ciws8Q1Po6Ezw7v7aUYHAVufGcpq+KJoIDFFUs+PilRT+4W/ZtzwRrs5ujqW9zoafxUVUa7Q9NrCASa9W6o+S/tavGkpRlarPoZWuKPn2OCc07xuIorw0w/YdxAQLyyU13KZVqi5Lf5QddE65MDJ+jzPJYz0hO/YUsjMrDygzFVrDi27nWRhkGBrNbiye
  template:
    metadata:
      creationTimestamp: null
      name: paperless-secret
      namespace: paperless
