---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCOJCW98tSQDPTSdahlOV6QvG1SlBKkD5KBQHlsD3g6fTVI/526d3rsvfrHr1dEdMuVQ59D9rwhsu7bHE1RI/N7abBIxE0jgr3Mi+GDykrFF3Pb9blZ/+r8hQ2LucbV5+CCOoQvYn6iGZi2V467fawIrLiCeUmWxukdWMfaJtYw9dB4eqUnimruLvGF9ZfXAxx9Qm4tikvCFS/VI5Rm+y1UlTEUh4TjCkH9jZyeqzeO4jyzHkY9s16wNrnkmsfFII838+i/vewP6DBsQylNkFAm/s+oRxZO/jVwFH7klS+xQ2Hdq/ElOhmgTrEWiojybxfTX4CjGUrANfjKzYJWCuO54QNOCOVUd/ZDzxyCNt1WtAm75tcUGklSjyvaOesLz07VWXW3KIQVsNbzbNifgQEzn3jZOdT+0OPfKPirDfSazPVRfcRjAge4+FjBe+NigfsnK3Mr/4WZHJeuQEU3z+mR51G+nxaNwp84+yLHoCre7oPCeoyuJECr+RyIwhTFv17wgcGEWHb+G2NOHd+MaWr8oLn5TND7TXIQNCNybXZDy8zgPvTjvzQhy38vy7aEqdXjsyreAHhhw/TjVIDePN9E9I7xpE8it5AiOhlZDN7KKPUAFFUUQdHqDCTbDVjhjfhLptIcZN6uC+JFYMFZBEBDOkzjDRSjXmTwNNU0MZcOoh5111B8kXdRb1ZXrEhhuplraSfPW1l5LBk7zC1FeYm5mHuwrtwkgERrao3Ja4pFcUDaHI5gfxVV
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager



  # kubectl create secret generic cloudflare-api-token \
  #   --from-literal=api-token="${CF_TOKEN}" \
  #   -n cert-manager --dry-run=client -o yaml \
  # | kubeseal --cert sealed-secrets-fixed-key.pem -o yaml \
  # > cluster/apps/system/cert-manager/templates/cloudflare-api-token.yaml