apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: restic-secret
  namespace: syncthing
spec:
  encryptedData:
    RESTIC_PASSWORD: AgCmryjCrtEJwwl3AqO9T1vAs8eY4UJOa6jb+Z3tofobUoO4QiC4NzRtWn5GVQFEO2vTOpSAbGi/IMXpoZnmtpgumczF0fafFwc4mzwi/Nwh5o/A2YtTUKsm4m+VHuRI3cTUMRfwDEkcCU8Msf77UDxNU/alMY7ExN5dbiZ5m2nA4ESSbzZY83uqcJ6WxbIXLS2FtdPNfTHZ4xb3N0xmbTMfDnaDgWzQ91BbKdOnp3aSmGvAvfVlU10iMHxzYQ4NcE/ZfBoFoZvDuW6Cu4LncpZ45KzsZu/abVLSB3ffWyFYyMp1kFCbfsWQcqngvRWxV82joE0b8GKg3boWRGCldkqriMFiWz31PyzXlE229+u28MVzePXoRI43KFRZIawDcm4UvKWnLfSYlorhQ8UskdOm46S3ZzdgVMk5v/MxkDXQ0uJge3GB9+YKyGlg5VhIB97gqQNhGLVJ73ELdt0hDZ5/L/jVlwMdC5Ffv16HvbRaoCnHSVltrOI6jrkZuCquISMT6WI6lf7CasKJJRFDAiBK0f0oohcinOAdisEkv1gy/tf8mKn8+mbNfJWPQSc73X1XeWNplUXBA6LRn23fjvZHoSKn0u3j8tR52AhpK8bH/nW9FvpKk93SXk4we4vleM9reIw7F6BuhiAID+uluRuuWZ8zFiZJaJ4xzZD8mgS2SwJm/K5c4dox25/fyccML03ZDVx8yTtfsdV/6olp0cJZgsNvIihvmHW+A9hmku/oOJjVuv/Roeek
  template:
    metadata:
      creationTimestamp: null
      name: restic-secret
      namespace: syncthing