---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone-config
  namespace: syncthing
spec:
  encryptedData:
    rclone.conf: AgBIs3v8YyK13k3MmErPCZG7Hz0lRfgod0nuTkH3hI1TRFS9GJfmlzRNc6X0QwPWBJL+gMNUfFVNeehL00r/EKTvWERYLUsbtU9+5A2Gg0LlUcWK0uB+4AwZBy5piyNii9M+vDedtFnqyyfkZky03Ad4nK3yXNqX/oU4u4pt+PUzp1+0L9HxE6hdrO92OT/Qel1OHIXSu7k7sHw1LHCara6pJIvNypi/TAwnprMMWCjnrxF9N9V/7ON5DvNfYH9lnEwUsSzmIYgAZ/vZKs4vf7JMP5HvNBM6nG9lhT90y8o0dsdFUberhvFNYuZMLuLZY7mywh04nOvVLKQYLUhKfZObzgZKz72MbcF3c6eZ7D0xgQPsY8re/WQ016ElqxCOlwKvVNR2keyr7TiBOExaTlj/9gkaIsJ8PLXyBH2NOiLKiAIuWPjVUqS1RdCiODloWuVKS72i4Ao52kcsqywvmaRjVD9HT+KlcaBgu7IobkkDI6js1kCbUJN2vj7qVlYzI3heuMwg4AP2fZfeUezAiv3M0HXER3j2/rJEdBTIdqhYQ/Hn1VJwCdHjxroHOJufFrWWw6mTQRxdZ0FZwfVqNlfznjVH2uF1hGqVRsJJXPGEv9067FYEuVIKpyMx1h8gMU4pedy06Bb2u8BYIypAMeBdpj1eVT5CbxbzM978vgK6PNjJPsKuf+Hn8hiJknVR2jmAjcBoK4XEpm68wG9KSPBOEwk5DVYXY7pjFB/1g/Nk4kBv5b0f9Ldhmgx4NlslsjizGcoNR0hO/g/NwGcINCo5LVGzJPZvB/Kq0XO3UZo2WeqIsZflgGA8Ph+6y0KKu7oOliKxmn4PQ7akGlmvE81HftQLrIQCx9Kn3D130OafQBPIqqbNXfHr74/sRg5Zbhy9ffewtXzK1/WtsekOoCrGvAezwp9BgKXU7j3C6dpXDAJF05ZdO6yjHCy5iaywEu9rjxC0VMQ/wjexZKamvA8xUX133OqdTYa837+vDDxLQ+erznTmlfeEeBnNyP+cObwVbw6Hl0NKmeNK9ZPk00NbO1NnVK0OpNZLupNTV7E3G8mMwztPQhRRyK+DGIl7IKh8sIQH+5frTyDgltlFIfOyL+TJMtQQVzXm2zRydKJKo+HbPq4zAw5kdhRBEKPEH2hPhfQVL9YSh+BG+lgcM46R49IMArPFv/DrOpUc966jNhyP7H1NxnHvZN7Z2jeg8cFGt2erOp0L3ZG9aFOsu8+oXU0ARHV3hG7V3U9q+6HG9mRY5p3wBnVsm4ac8vdUxkZbtqQaD/Zem7+E/VG01s8hwmzdfkYNfpU6OP7cx6FHKQvEeFvWHiG6fqIWadMzcUAYZh7Hf63QA362t+wLJiUcWkDYNBxsjf0YAuY55i1jnQFbb9ErWel3TPBoAqVeF2zmV6xVeEz46ST5d9wmlMqlZuQp2lb+wcVPHUdPQuDo9h69TuNlkIEDD0z+vgQSt5V34Www7sjf4XcIrlcWSDqIMhSHgmlC06BNuOcnHSeuYg+nV+x+9nWb8+wggUBbSdt2kHlu/oAcG7ImEs6lh706ii2W+PiNhcmymceV2kkZyxTZTyMw
  template:
    metadata:
      name: rclone-config
      namespace: syncthing

  # kubectl create secret generic rclone-config \
  #   --from-file=rclone.conf="${RCLONE_CONF}" \
  #   -n syncthing --dry-run=client -o yaml \
  # | kubeseal --cert sealed-secrets-fixed-key.pem -o yaml \
  # > cluster/apps/syncthing/backup-rclone-secret.yaml