---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: restic-secret
  namespace: syncthing
spec:
  encryptedData:
    RESTIC_PASSWORD: AgCLIjpoCxPQRmQ6dBvHGAnkqmWSc+ZZK8n5JrHLD7ZhTGCiJtmhL+fbZB4UYkuXVKWdoAVfFEc+qnyz/sc88iCSIa+XRSlmlBFAnK0h6+p4//5WGDv+OpGOpjY3xhYIpvzXe2MYzYjdgbmsEGmaWhpfUIsoZ+6OyX/CAJ7dxWmgSuqTqnls26greLd1elyMcU3Hm4F2iUmj/DCeFMNDV59MmIicMWMKbPbI9+IksyuMu7du3WlA7YC5s2IqMzEhMGUhSPPx+Em99KENvGMk8llGV/ySRA+F62MG2/dSXZzdW9K7vJ7fxxi/du/VTnaFIJrZ18JJaKkJ6LNVyLcMLpozPAtGHXot4b3zBK//nOm0/YrAPnqP9RteLzcm8q5QABhB/SpMz/b2KXnQg3m8XPx/B5dOyCWwJPEZbGN4jtkJTr2vMiSlDCQ5I3+B+Yh08qGofeISLntiAx8zjQYtafgjyIotPZPm+gK3+X49FNjTyPVSFWOeJDVq3Tu/TrvovG+Wk4nEv6cYYaRcdBo73Wf6bmaZUyx3IKlfoD9sf1+5o8R7P0Fqf7dwWBUsmuYKAReNEd8Yzdd3RZyv6LecfBUtn9GTLWLSso826K2pNfbqZe+BP8JXd7xaVXWhhQKK+EwH5U20Fmg+4NNxb4d01+5Rae9ePh+whb7ad5og7ToX/Ykd8qk29lv5MJJDpfq/c6q0z3gVnbEfiemDj70f6yW/9Suo9XrCpaVKNdoEQ0G3fl42eeBr2UmC
  template:
    metadata:
      name: restic-secret
      namespace: syncthing

  # kubectl create secret generic restic-secret \
  #   --from-literal=RESTIC_PASSWORD="${RESTIC_PASS}" \
  #   -n syncthing --dry-run=client -o yaml \
  # | kubeseal --cert sealed-secrets-fixed-key.pem -o yaml \
  # > cluster/apps/syncthing/backup-restic-secret.yaml