---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: restic-secret
  namespace: syncthing
spec:
  encryptedData:
    RESTIC_PASSWORD: AgCOW5iwxyeBgP1o4a6Sz3s7Mt1cpxpJKIxdkEIRSh+pVBA33PbS771riPnLG1JsrLkZNmj0cJLP6uqiiSnDggKd1SxwUDdyy9DPX9BHAIEWVYA0/inA4vDjcPCgPAtlEjsaiHGHeoHF3QA6T5ldrVf7KVT3l9HI37EMYOtGQ9LFCzer9qM1KSktoLzYfNHMit9hKlCKKtMmReuKpnZcvoKjLh/Sm5s9swk75WpIgGsW+XRUtW5B+35pxVe3KVzNaOVG1mCNHGAt7qLbJDuWt1UHdORoh1iCi6cVRCgGsSoTCw1+0PytaQUk4L8EJlyUVV39g3S2v7VDUKmuZ4KH3i25wcvUIxeYtu3fjZYVVNFlkGr6DF7oovNsemVPgTDkp19fj9RMpXFtJUw2wJkIGa3KqeaKvKPzjVmfD7ot+hnsyV2gNCQW6pAAe4d+UO8yJI8wmOk/R98gFk6rxpaKLMsCuk/wj3q6xP+NTz3botCdCHyaCuYyrCdLtZgibzIFDebRVvdNe/PCuZEjLaild6zorjwXI8yT6LfynE3LDTLGjbAPf6jjqQSEjvfxyrmfgt4ymj/bgbToGQUcLwXdXLbYWKShp2zCBeAefRXUU73XVJ6qyrn6rvLUHPIV5Q4P4dgKyeVXl/ZORAByQyWl17718eDY5VmNBieDlIYeXsLOuQVfcbVW7jMjKSqK2tJH/7c=
  template:
    metadata:
      name: restic-secret
      namespace: syncthing

  # kubectl create secret generic restic-secret \
  #   --from-literal=RESTIC_PASSWORD="${RESTIC_PASS}" \
  #   -n syncthing --dry-run=client -o yaml \
  # | kubeseal --cert sealed-secrets-fixed-key.pem -o yaml \
  # > cluster/apps/syncthing/backup-restic-secret.yaml