ingress-nginx:
  controller:
    service:
      externalTrafficPolicy: Local
      loadBalancerSourceRanges:
        - 192.168.1.0/24
    config:
      # Applique cette restriction à TOUS les ingress par défaut
      whitelist-source-range: "192.168.1.0/24"
    annotations:
      metallb.io/address-pool: first-pool
      metallb.io/loadBalancerIPs: 192.168.1.250
    ingressClassResource:
      name: nginx
      enabled: true
      default: true
    # service:
    #   enabled: true
    #   type: LoadBalancer
    #   loadBalancerIP: "192.168.1.250"  # IP du pool MetalLB