ingress-nginx:
  controller:
    service:
      externalTrafficPolicy: Local
    annotations:
      metallb.io/address-pool: first-pool
      metallb.io/loadBalancerIPs: 192.168.1.250
    ingressClassResource:
      name: nginx
      enabled: true
      default: true
    # service:
    #   enabled: true
    #   type: LoadBalancer
    #   loadBalancerIP: "192.168.1.250"  # IP du pool MetalLB