apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shadowsocks-config
  namespace: gluetun
spec:
  encryptedData:
    password: AgC/6NlGJUBEGxX3kw6VPbE4MMSCNUD61O8C4n2Q/xaBhOXc6zon0Isc56r0gENWdBqMfpKZ8QSzk+Mk0ywBfrZqk2XIEtPO641t8lQqKNGAbNTzsOuR9vuIcZu7LvekdDHIAQCcc5w6o33r+XF/WCSDFpc9v3DBbMecWWcfb9nKNggpwy4z9uvfd/UauUuwNTH/WPIt9JT5c+6ZueQZGF3XDyp6FqB8iVGSwk9bNu130uTHPVy2QHtIseDRQeVzduwuODEiVg/vYZPK1Dj0Ni3sPbQghtUSM6Sbq7dhQ8rXBPVa7Pkm/H2YKe2PFRuwG2KPQmEKq3Yce3Gp00EHPygDxn51qn6R0m9MjQX/TUO8U0iaWEtJGSJgUHH9w4UxpgJyoIr+xw6uyQhvGUxamNmlmgZvFL/92PfUGWVez/BEU9P2FabOCM/CJu+XMcBpq+w9KL9rwhQ16YsbYoxhCVMUjd8/hvXzph7cP6Np+0mLb81qnEDr86UPF98hsCSdSFwTsf1lepKCFIktCCpz9kwYL6b4dmZHjccbGIta4rtM1u5YBhg1KMFubH0NruwMMOmUr7RBCZXfS+PIEkGdz2y7SCe/RAzRupmlleE20/KdGsItfKbWZfMC7wbXOs5O7q9P2ZNmSO3f6JsGHpfbO9EtqU2RG2WyfBf1aSyieWE0bgSREdYF2U75NQ4NpHOy0xmJ0cbBAQQ=
  template:
    metadata:
      creationTimestamp: null
      name: shadowsocks-config
      namespace: gluetun

  # kubectl create secret generic shadowsocks-config \
  #   --from-literal=password="${SS_PASS}" \
  #   -n gluetun --dry-run=client -o yaml \
  # | kubeseal -o yaml -n gluetun \
  # > cluster/apps/gluetun/shadowsocks-secret.yaml