---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: shadowsocks-config
  namespace: gluetun
spec:
  encryptedData:
    password: AgAEqUUQMhHe+dyjd1BKP5e+uPG0TGZXudEejbwSb7CdgTZTvkzFsqqYU4c8Hrh4VaQppQQ6GptBAJEsJA4dTUdXdmdQ/NWzclHhp36Cbq1+xLfPNNo3rSMrG9RxvUrE2nhTuI9IJ1Mptk9ljAuYh2v00eAWkeQol1+uZnkVWHmKUSWLLZPecMfhDnTt6EcELPYC8Eiu+xRvH0uFXjeKY8tixviC6axPHtc7FVK7or5v5LFENfhBq+/niV9JPGEesB35KDenDrqwqFvmfXDVmOriPcmdEL4e7vwc95CQh/B6/cNHBTFmiJ7kc3XxIJS5V4Irrca1iGunbEVlWtZhwDxVRMOvgjb9euwo7cck+ayYgsRwWTwqdBZeGNJ3L2mai3b8KWWhQaEnfdo+aB2fq6ZKB0ATikgt2WeZHQCdab+pmtviAwVZMuVFdOHOglgWrEd8JIXBGnNEOhKqReVS+1+KDUSo2vfw0OZwBkenr7uEdzY0+MF6hXhQBC/YJtXUEjh1QEtp5id1CuTSuvJENUH2E0/1N0Y09chkfqCkMw2sorBq+veTFaKZNMNbDBUsn5c4UtQKA/fzhnPRABM8gNMmaTkX2RJu1hYOOws/PmnQ2OrQKfVlS2sr8xwF+ph8W+1t36Qwn1eHirW9jtOGeXNOQ5jG5LnTROPdZQrqirZUIMyFHZzhsQ4YAYG+5EpVGgD2NJlCMDk=
  template:
    metadata:
      name: shadowsocks-config
      namespace: gluetun

  # kubectl create secret generic shadowsocks-config \
  #   --from-literal=password="${SS_PASS}" \
  #   -n gluetun --dry-run=client -o yaml \
  # | kubeseal -o yaml -n gluetun \
  # > cluster/apps/gluetun/shadowsocks-secret.yaml