apiVersion: v1
kind: Service
metadata:
  name: vpn-service
spec:
  selector:
    app: vpn-gateway
  ports:
    - name: http-proxy
      protocol: TCP
      port: 8888
      targetPort: 8888
    - name: socks-proxy
      protocol: TCP
      port: 1080
      targetPort: 1080
